export const WNPErrors = {
  MANIFEST_INVALID: 'WNP_MANIFEST_INVALID',
  POLICY_VIOLATION: 'WNP_POLICY_VIOLATION',
  PAYMENT_REQUIRED: 'WNP_PAYMENT_REQUIRED',
  PAYMENT_FAILED: 'WNP_PAYMENT_FAILED',
  NO_PAYMENT_PROVIDER: 'WNP_NO_PAYMENT_PROVIDER',
  BUDGET_EXCEEDED: 'WNP_BUDGET_EXCEEDED',
  TOKEN_EXPIRED: 'WNP_TOKEN_EXPIRED',
  TOKEN_INVALID: 'WNP_TOKEN_INVALID',
  DUPLICATE_CONTENT: 'WNP_DUPLICATE_CONTENT',
  RATE_LIMITED: 'WNP_RATE_LIMITED',
  BYPASS_ATTEMPT: 'WNP_BYPASS_ATTEMPT',
} as const
